name: Manual workflow triggiering

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubunut-latest

    steps:
      - name: Run a script
        run: |
          echo "This is a manually triggered workflow."
