name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hi I'm triggered manually to deploy to ${{ github.event.inputs.environment }} environment!"
