name: Set Warning

on: 
    workflow_dispatch:

jobs:
  warning_job:
    runs-on: ubuntu-latest

    steps:
      - name: Warinig
        run: |
            deprecated=true
            if [ "$deprecated" = true ]; then
              echo "::warning:: This step is deprecated."
            else
              echo "This step is not deprecated."
            fi